# dltrf.ps1 - DLTRF CLI (PowerShell wrapper for Windows)

param([string]$Command = "help")

# Allow native commands (Docker/WSL) to print to stderr without crashing
$ErrorActionPreference = "Continue"

function PrintInfo($m)   { Write-Host "  * $m" -ForegroundColor Cyan }
function PrintOk($m)     { Write-Host "  + $m" -ForegroundColor Green }
function PrintWarn($m)   { Write-Host "  ! $m" -ForegroundColor Yellow }
function PrintFail($m)   { Write-Host "  X $m" -ForegroundColor Red; exit 1 }
function PrintHeader($m) {
    Write-Host "`n  ======================================" -ForegroundColor Blue
    Write-Host "   DLTRF - $m" -ForegroundColor Blue
    Write-Host "  ======================================`n" -ForegroundColor Blue
}

# DYNAMIC PATHS (Automatically detects where this script is saved)
$RootDir = $PSScriptRoot
if (-not $RootDir) { $RootDir = $PWD.Path } 

$HookDir   = Join-Path $RootDir "universal-logging-hook-microservice"
$EngineDir = Join-Path $RootDir "replay-engine"

$ConfigFile  = Join-Path $RootDir "dltrf.config.yaml"
$DltrfYaml   = Join-Path $HookDir "dltrf.yaml"
$EngineYaml  = Join-Path $EngineDir "dltrf.yaml"
$RedisC      = "universal-logging-redis"
$StreamKey = "nginx-log-stream"
$EngineApi   = "http://localhost:8000"
$EngineToken = "mysecret"

function GetCfg($key, $default = "") {
    if (-not (Test-Path $ConfigFile)) { return $default }
    $line = Select-String -Path $ConfigFile -Pattern "^\s*${key}\s*:" | Select-Object -First 1
    if ($line) { return ($line.Line -replace ".*:\s*", "").Trim().Trim('"').Trim("'") }
    return $default
}

function GetCfgNested($parentDotChild, $default = "") {
    if (-not (Test-Path $ConfigFile)) { return $default }
    $parts  = $parentDotChild.Split(".", 2)
    $parent = $parts[0]; $child = $parts[1]
    $lines  = Get-Content $ConfigFile
    $inBlock = $false
    foreach ($line in $lines) {
        if ($line -match "^${parent}\s*:") { $inBlock = $true; continue }
        if ($inBlock -and $line -match "^\s+${child}\s*:") {
            return ($line -replace ".*:\s*", "").Trim().Trim('"').Trim("'")
        }
        if ($inBlock -and $line -match "^\S") { $inBlock = $false }
    }
    return $default
}

function GetRedisCount {
    try { 
        return [int](docker exec $RedisC redis-cli XLEN $StreamKey 2>$null) 
    } catch { 
        return 0 
    }
}

function RequireConfig {
    if (-not (Test-Path $ConfigFile)) { PrintFail "dltrf.config.yaml not found. Run: .\dltrf.ps1 init" }
}

function RequireDirs {
    if (-not (Test-Path $HookDir)) { PrintFail "Logging hook not found at $HookDir" }
    if (-not (Test-Path $EngineDir)) { PrintFail "Replay engine not found at $EngineDir" }
}

function GenerateDltrfYaml {
    $host_     = GetCfgNested "target.host" "my-app"
    $port_     = GetCfgNested "target.port" "3000"
    $proto     = GetCfgNested "target.protocol" "http"
    $dbType    = GetCfgNested "database.type" "sqlite"
    $dbCont    = GetCfgNested "database.container" $host_
    $dbName    = GetCfgNested "database.name" "app"
    $dbUser    = GetCfgNested "database.user" "root"
    $dbPass    = GetCfgNested "database.password" ""
    $proxyPort = GetCfg "proxy_port" "3000"
    $profile   = GetCfg "profile" ""

    $lines = @(
        "# Auto-generated by dltrf CLI",
        "target:",
        "  host: $host_",
        "  port: $port_",
        "  protocol: $proto",
        "",
        "state_management:",
        "  type: $dbType"
    )

    if ($dbType -in @("mysql","mariadb")) {
        $lines += "  container: $dbCont"
        $lines += "  mysql:"
        $lines += "    container: $dbCont"
        $lines += "    user: $dbUser"
        $lines += "    password: $dbPass"
        $lines += "    database: $dbName"
        $lines += "  checkpoint_name: baseline"
    }
    if ($dbType -in @("postgres","postgresql")) {
        $lines += "  container: $dbCont"
        $lines += "  postgres:"
        $lines += "    container: $dbCont"
        $lines += "    user: $dbUser"
        $lines += "    password: $dbPass"
        $lines += "    database: $dbName"
        $lines += "  checkpoint_name: baseline"
    }
    if ($dbType -eq "sqlite") {
        $sqlitePath = GetCfgNested "database.sqlite_path" "/app/data/database.sqlite"
        $lines += "  container: $dbCont"
        $lines += "  sqlite_path: $sqlitePath"
        $lines += "  checkpoint_name: baseline"
    }

    $lines += ""
    $lines += "divergences:"
    $lines += "  custom_rules: []"
    $lines += ""
    $lines += "hooks:"
    $lines += "  before_record: ''"
    $lines += "  after_record:  ''"
    $lines += "  before_replay: ''"
    $lines += "  after_replay:  ''"

    $lines | Set-Content $DltrfYaml -Encoding ASCII
    $lines | Set-Content $EngineYaml -Encoding ASCII

    # ── .env for logging hook (TARGET_HOST/TARGET_PORT drives OpenResty proxy) ─
    $envLines = @(
        "TARGET_HOST=$host_",
        "TARGET_PORT=$port_",
        "PROXY_PORT=$proxyPort",
        "REDIS_URL=redis://universal-logging-redis:6379",
        "STREAM_KEY=nginx-log-stream",
        "REPLAY_SHARED_TOKEN=mysecret"
    )
    $envLines | Set-Content (Join-Path $HookDir ".env") -Encoding ASCII

    # ── .env for replay engine (TARGET_HOST/TARGET_PORT builds TARGET_APP_URL) ─
    $envLines | Set-Content (Join-Path $EngineDir ".env") -Encoding ASCII

    PrintOk "dltrf.yaml generated"
    PrintOk ".env injected (hook + engine)"

    # ── Copy divergence profile → replay-engine/divergence_config.yaml ───────
    if ($profile) {
        $profileAbsolute = Join-Path $RootDir $profile
        $destProfile     = Join-Path $EngineDir "divergence_config.yaml"

        if (-not (Test-Path $profileAbsolute)) {
            PrintWarn "Profile not found: $profileAbsolute"
            PrintWarn "divergence_config.yaml was NOT updated. Fix 'profile:' in dltrf.config.yaml"
        } else {
            Copy-Item -Path $profileAbsolute -Destination $destProfile -Force
            PrintOk "Divergence profile loaded: $profile -> replay-engine/divergence_config.yaml"
        }
    } else {
        PrintWarn "'profile:' not set in dltrf.config.yaml — divergence_config.yaml not updated."
    }
}

function RunInit {
    PrintHeader "Init"
    if (Test-Path $ConfigFile) { PrintWarn "Config exists."; return }
    $appName = Split-Path $PWD -Leaf
    
    $cfgLines = @(
        "name: '$appName'",
        "target:",
        "  host: bookstack",
        "  port: 80",
        "  protocol: http",
        "proxy_port: 3000",
        "# profile: path to the divergence rule profile for this app.",
        "# Copy profiles/bookstack.yaml as a starting point for new apps.",
        "profile: 'profiles/bookstack.yaml'",
        "database:",
        "  type: mysql",
        "  container: bookstack-db",
        "  name: bookstack",
        "  user: bookstack",
        "  password: bookstack",
        "recording:",
        "  max_events: 200"
    )
    $cfgLines | Set-Content $ConfigFile -Encoding ASCII
    PrintOk "Created dltrf.config.yaml"
    PrintInfo "Edit 'target.host', 'database', and 'profile' for your app, then run: .\dltrf.ps1 up"
}

function RunUp {
    PrintHeader "Starting All Components"
    RequireConfig
    RequireDirs
    GenerateDltrfYaml

    PrintInfo "Booting universal-logging-hook-microservice..."
    Push-Location $HookDir
    docker compose up -d
    $hookStatus = $LASTEXITCODE
    Pop-Location

    if ($hookStatus -ne 0) {
        PrintFail "Failed to start universal-logging-hook-microservice. Check Docker errors above."
    }

    PrintInfo "Booting replay-engine..."
    Push-Location $EngineDir
    docker compose up -d
    $engineStatus = $LASTEXITCODE
    Pop-Location

    if ($engineStatus -ne 0) {
        PrintFail "Failed to start replay-engine. Check Docker errors above."
    }

    PrintOk "All DLTRF services are successfully running."
}

function RunDown {
    PrintHeader "Tearing Down All Components"
    RequireDirs

    PrintInfo "Stopping universal-logging-hook-microservice..."
    Push-Location $HookDir
    docker compose down --remove-orphans 2>&1 | Out-Null
    Pop-Location

    PrintInfo "Stopping replay-engine..."
    Push-Location $EngineDir
    docker compose down --remove-orphans 2>&1 | Out-Null
    Pop-Location

    PrintOk "All DLTRF containers stopped and removed."
}

function RunBuild {
    PrintHeader "Rebuilding All Components"
    RequireConfig
    RequireDirs
    GenerateDltrfYaml

    PrintInfo "Building universal-logging-hook-microservice..."
    Push-Location $HookDir
    docker compose build
    Pop-Location

    PrintInfo "Building replay-engine..."
    Push-Location $EngineDir
    docker compose build
    Pop-Location

    PrintOk "All images rebuilt successfully."
}

function RunRecord {
    PrintHeader "Record"
    RequireConfig
    RequireDirs

    $appName   = GetCfg "name" "my-app"
    $proxyPort = GetCfg "proxy_port" "3000"

    PrintInfo "App: $appName"
    PrintInfo "Generating framework config..."
    GenerateDltrfYaml

    PrintInfo "Starting logging stack..."
    Push-Location $HookDir
    docker compose down --remove-orphans 2>&1 | Out-Null
    docker compose up -d 
    $upStatus = $LASTEXITCODE
    Pop-Location

    if ($upStatus -ne 0) {
        PrintFail "Logging stack failed to start. Recording aborted."
    }

    PrintInfo "Waiting for Redis..."
    Start-Sleep -Seconds 4
    
    $currentEvents = GetRedisCount
    if ($currentEvents -gt 0) {
        Write-Host ""
        PrintWarn "Redis already contains $currentEvents recorded events."
        $ans = Read-Host "  ? Do you want to clear them and start fresh? (Y/n)"
        if ($ans -eq 'n' -or $ans -eq 'N') {
            PrintOk "Appending to existing logs..."
        } else {
            docker exec $RedisC redis-cli FLUSHALL | Out-Null
            PrintOk "Redis cleared. Starting fresh."
        }
    } else {
        docker exec $RedisC redis-cli FLUSHALL | Out-Null
        PrintOk "Redis cleared."
    }

    Write-Host "`n  ----------------------------------------------" -ForegroundColor Green
    Write-Host "    Recording started                           " -ForegroundColor Green
    Write-Host "    Browse your app: http://localhost:$proxyPort" -ForegroundColor Green
    Write-Host "    Press ENTER when done.                      " -ForegroundColor Green
    Write-Host "  ----------------------------------------------`n" -ForegroundColor Green
    Read-Host

    $count = GetRedisCount
    PrintOk "$count total events recorded`n"
    PrintInfo "Next step: Run .\dltrf.ps1 replay"
}

function RunCheckpoint {
    PrintHeader "Checkpoint"
    RequireConfig
    RequireDirs

    # SQLite apps (e.g. JuiceShop) maintain state in-process.
    # Checkpointing them requires a container restart which regenerates
    # the JWT signing key and invalidates all recorded tokens.
    # For SQLite, the checkpoint command is a no-op by design.
    $dbType = GetCfgNested "database.type" "sqlite"
    if ($dbType -eq "sqlite") {
        PrintWarn "SQLite app detected — checkpoint is not applicable."
        PrintInfo "JuiceShop and other SQLite apps keep state in-memory."
        PrintInfo "No checkpoint file will be created. Replay will use the live container as-is."
        return
    }

    $script = Join-Path $EngineDir "scripts\checkpoint.sh"
    if (-not (Test-Path $script)) { PrintFail "Script not found at $script" }

    $driveLetter = $EngineDir.Substring(0,1).ToLower()
    $pathRest    = $EngineDir.Substring(2).Replace("\","/")
    $wslPath     = "/mnt/$driveLetter$pathRest"

    PrintInfo "Saving DB checkpoint via WSL..."
    $bashCmd = "cd '$wslPath' ; chmod +x scripts/checkpoint.sh ; ./scripts/checkpoint.sh save"
    wsl -d Ubuntu -e bash -c $bashCmd
    
    if ($LASTEXITCODE -eq 0) { PrintOk "Checkpoint saved" }
    if ($LASTEXITCODE -ne 0) { PrintWarn "Checkpoint failed (Code $LASTEXITCODE)" }
}

function RunReplay {
    PrintHeader "Replay"
    RequireConfig
    RequireDirs

    $maxEvents = GetCfgNested "recording.max_events" "200"
    $dbType    = GetCfgNested "database.type" "sqlite"

    $running = docker ps --format "{{.Names}}" 2>$null | Select-String "^replay-engine$"
    
    if (-not $running) {
        PrintInfo "Starting replay-engine..."
        Push-Location $EngineDir
        docker compose up -d --build
        Pop-Location
        Start-Sleep -Seconds 6
    }

    $cpDir = Join-Path $EngineDir "checkpoints"
    $hasCp = (Test-Path $cpDir) -and ((Get-ChildItem $cpDir -Filter "*.sql" -ErrorAction SilentlyContinue).Count -gt 0)

    # ── CHECKPOINT RESTORE ────────────────────────────────────────────────────
    # SQLite apps (JuiceShop etc.) use an in-memory/file SQLite DB.
    # Restoring a checkpoint restarts the target container, which causes
    # Node.js to regenerate a new RSA keypair for JWT signing.
    # Every recorded Bearer token then becomes cryptographically invalid,
    # making 100% of authenticated replays fail with 401.
    # Solution: skip restore entirely for SQLite. The container stays alive,
    # the JWT secret is preserved, and recorded tokens remain valid.
    # ─────────────────────────────────────────────────────────────────────────
    if ($dbType -eq "sqlite") {
        PrintInfo "SQLite app — skipping checkpoint restore to preserve JWT signing key."
        PrintInfo "Target container will NOT be restarted. Recorded tokens remain valid."
    } elseif ($hasCp) {
        PrintInfo "Restoring DB checkpoint..."
        $driveLetter = $EngineDir.Substring(0,1).ToLower()
        $pathRest    = $EngineDir.Substring(2).Replace("\","/")
        $wslPath     = "/mnt/$driveLetter$pathRest"

        $bashCmd = "cd '$wslPath' ; ./scripts/checkpoint.sh restore"
        wsl -d Ubuntu -e bash -c $bashCmd

        if ($LASTEXITCODE -eq 0) { PrintOk "DB checkpoint restored" }
        if ($LASTEXITCODE -ne 0) { PrintWarn "Restore failed (Code $LASTEXITCODE)" }

        PrintInfo "Waiting 10s for app container to boot..."
        Start-Sleep -Seconds 10
    } else {
        PrintWarn "No checkpoint found — replaying against current DB state."
    }

    PrintInfo "Starting replay..."
    $authHeaders = @{ "Authorization" = "Bearer $EngineToken"; "Content-Type" = "application/json" }
    $bodyJson    = @{ mode = "replay"; max_events = [int]$maxEvents; start_ts = "0"; end_ts = "+" } | ConvertTo-Json -Compress
    
    try {
        $response = Invoke-RestMethod -Uri "$EngineApi/replay/start" -Method POST -Headers $authHeaders -Body $bodyJson -ErrorAction Stop
        $replayId = $response.replay_id
        PrintOk "Replay started - ID: $replayId"
    } catch {
        PrintFail "Could not reach replay API. Is the replay-engine container running?"
    }

    PrintInfo "Waiting for report..."
    $reportInContainer = "/app/reports/replay_$replayId.html"
    $elapsed = 0
    $found   = $false
    while ($elapsed -lt 300) {
        Start-Sleep -Seconds 2
        $elapsed += 2
        docker exec replay-engine test -f $reportInContainer 2>$null
        if ($LASTEXITCODE -eq 0) { $found = $true; break }
        Write-Host "." -NoNewline -ForegroundColor DarkCyan
    }
    Write-Host ""

    if (-not $found) {
        PrintWarn "Grabbing latest report..."
        $latest = docker exec replay-engine sh -c "ls -t /app/reports/*.html 2>/dev/null | head -1"
        $latest = $latest.Trim()
        if (-not $latest) { PrintFail "No report found." }
        $reportInContainer = $latest
        $replayId = [System.IO.Path]::GetFileNameWithoutExtension($latest) -replace "^replay_", ""
    }

    $reportDir  = Join-Path $PWD "dltrf-reports"
    New-Item -ItemType Directory -Force -Path $reportDir | Out-Null
    $localReport = Join-Path $reportDir "replay_$replayId.html"
    docker cp "replay-engine:$reportInContainer" $localReport
    PrintOk "Report saved: $localReport"

    Start-Process $localReport
    Write-Host "`n  + Done - ID: $replayId" -ForegroundColor Green
}

function RunStatus {
    PrintHeader "Status"
    $count = GetRedisCount
    PrintInfo "Redis events : $count"
    Write-Host ""
    PrintInfo "Containers:"
    docker ps --format "  {{.Names}}`t{{.Status}}" 2>$null
}

# ─────────────────────────────────────────────────────────────────────────────
# Factory Reset — nukes all volumes and boots a completely fresh stack
# ─────────────────────────────────────────────────────────────────────────────
function RunReset {
    PrintHeader "Factory Reset (Blank Slate)"
    RequireDirs

    PrintWarn "This permanently destroys ALL containers, volumes, and recorded data."
    $confirm = Read-Host "  Are you sure? (y/N)"
    if ($confirm -ne "y" -and $confirm -ne "Y") { PrintInfo "Cancelled."; return }

    PrintInfo "Destroying all containers and persistent volumes..."
    Push-Location $HookDir
    # The -v flag permanently deletes the database and image hard drives!
    docker compose down -v
    Pop-Location

    PrintInfo "Booting a completely fresh environment..."
    Push-Location $HookDir
    docker compose up -d
    Pop-Location

    Write-Host ""
    PrintOk "Wipe complete! Your app is currently reinstalling from scratch."
    PrintWarn "Please wait 45-60 seconds before visiting http://localhost:$(GetCfg 'proxy_port' '3000')"
    PrintWarn "Default Login: admin@admin.com / password"
    Write-Host ""
}

function RunReport {
    PrintHeader "Report"
    $reportDir = Join-Path $PWD "dltrf-reports"
    $latest = Get-ChildItem $reportDir -Filter "*.html" -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if (-not $latest) { PrintFail "No reports found." }
    PrintInfo "Opening: $($latest.FullName)"
    Start-Process $latest.FullName
}

function RunHelp {
    Write-Host @"

  DLTRF - Deterministic Log Test Replay Framework
  Usage: .\dltrf.ps1 <command>

  Commands:
    init        Create config template
    checkpoint  Snapshot the CLEAN database (MySQL/Postgres only; no-op for SQLite)
    record      Start proxy, flush Redis, wait for browse
    replay      Restore checkpoint (if applicable), run replay, open report
    status      Show health and event count
    report      Open latest HTML report

  Lifecycle Commands:
    up          Start all containers for both components
    down        Stop and remove all containers
    build       Force rebuild Docker images for both components
    reset       Factory reset — wipe all volumes and boot fresh

  Database type behaviour:
    mysql/postgres  checkpoint save+restore is active (DB state is reset before replay)
    sqlite          checkpoint restore is SKIPPED (container stays alive, JWT key preserved)

"@
}

switch ($Command.ToLower()) {
    "init"        { RunInit }
    "record"      { RunRecord }
    "stop"        { $count = GetRedisCount; PrintOk "$count events in Redis" }
    "checkpoint"  { RunCheckpoint }
    "replay"      { RunReplay }
    "status"      { RunStatus }
    "reset"       { RunReset }
    "report"      { RunReport }
    "up"          { RunUp }
    "down"        { RunDown }
    "build"       { RunBuild }
    "help"        { RunHelp }
    default       { PrintWarn "Unknown command"; RunHelp; exit 1 }
}