"""
REPLAY-ENGINE/analysis/report_generator.py
DLTRF report generator — builds the HTML report from replay output.

ARCHITECTURE:
  This module contains ZERO app-specific logic. All classification rules,
  text strings, and app-specific knowledge live in divergence_config.yaml.
  This file is a pure renderer: it evaluates rules and renders HTML.

CLASSIFICATION PIPELINE (in order of precedence):
  1. custom_rules (top-to-bottom, first match wins)
  2. global_noise.status_transitions
  3. Engine's original tier (INVESTIGATE / CRITICAL) — no match fallback

VERDICT LOGIC:
  - PASS   : rate >= 95% AND nc_unclassified == 0
             (classified CRITICAL items with known rules do NOT trigger FAIL)
  - REVIEW : rate >= 95% but nc_unclassified > 0, OR rate 80-94%
  - FAIL   : rate < 80%

  nc_unclassified = items in critical_final where rule_id == "no_match"
  nc              = total critical items (shown in UI tabs, includes classified ones)

To add a new rule for your app: edit divergence_config.yaml.
Do not edit this file for app-specific behaviour.
"""

import fnmatch
from jinja2 import Environment, BaseLoader
from typing import Any, Dict, Optional, Tuple


# ── Status code metadata ──────────────────────────────────────────────────────
_STATUS: Dict[int, Tuple[str, str]] = {
    200: ("OK",                 "#16a34a"),
    201: ("Created",            "#16a34a"),
    204: ("No Content",         "#16a34a"),
    301: ("Moved Permanently",  "#2563eb"),
    302: ("Found (Redirect)",   "#2563eb"),
    304: ("Not Modified",       "#2563eb"),
    400: ("Bad Request",        "#d97706"),
    401: ("Unauthorized",       "#d97706"),
    403: ("Forbidden",          "#d97706"),
    404: ("Not Found",          "#d97706"),
    405: ("Method Not Allowed", "#d97706"),
    419: ("CSRF Mismatch",      "#d97706"),
    422: ("Unprocessable",      "#d97706"),
    429: ("Rate Limited",       "#d97706"),
    500: ("Server Error",       "#dc2626"),
    502: ("Bad Gateway",        "#dc2626"),
    503: ("Unavailable",        "#dc2626"),
    0:   ("No Response",        "#6b7280"),
}


def _status_info(code: Any) -> Tuple[str, str]:
    try:
        c = int(code)
        if c in _STATUS:
            return _STATUS[c]
        if c == 0:  return ("", "#6b7280")
        if c < 300: return ("", "#16a34a")
        if c < 400: return ("", "#2563eb")
        if c < 500: return ("", "#d97706")
        return ("", "#dc2626")
    except (TypeError, ValueError):
        return ("", "#6b7280")


_METHOD_COLORS = {
    "GET":    "#3b82f6",
    "POST":   "#22c55e",
    "PUT":    "#eab308",
    "DELETE": "#ef4444",
    "PATCH":  "#a855f7",
}

_TIER_COLORS = {
    "EXPECTED":    "#16a34a",
    "INVESTIGATE": "#d97706",
    "CRITICAL":    "#dc2626",
}


# ── Human-readable action label ───────────────────────────────────────────────
def _what_user_did(method: str, path: str) -> str:
    p = path.lower()
    m = method.upper()

    if any(x in p for x in ("login", "signin", "sign_in")) and m == "POST":
        return "🔑 Logged in"
    if "logout" in p or "signout" in p:
        return "🚪 Logged out"
    if any(x in p for x in ("register", "signup", "sign_up")) and m == "POST":
        return "📝 Registered"
    if "basket" in p or "cart" in p:
        if any(x in p for x in ("checkout", "purchase", "order/place")) and m == "POST":
            return "💳 Placed order"
        if m == "DELETE":  return "🗑 Removed from cart"
        if m == "POST":    return "🛒 Added to cart"
        return "👀 Loaded cart"
    if "order" in p and m == "POST":        return "📦 Placed order"
    if "checkout" in p and m == "POST":     return "💳 Checked out"
    if "address" in p:
        return "📍 Saved address" if m in ("POST", "PUT") else "👀 Loaded addresses"
    if any(x in p for x in ("card", "payment", "paymentmethod")):
        return "💳 Saved payment" if m in ("POST", "PUT") else "👀 Payment options"
    if "wallet" in p:
        return "💰 Loaded wallet" if m == "GET" else "💰 Updated wallet"
    if "delivery" in p:
        return "🚚 Delivery options"
    if any(x in p for x in ("whoami", "profile", "me", "account")):
        return "👤 Loaded profile"
    if any(x in p for x in ("shelves", "shelf")):
        return "📚 Browsed shelves" if m == "GET" else "📚 Shelf action"
    if any(x in p for x in ("books", "/book/")):
        return "📖 Browsed books" if m == "GET" else "📖 Book action"
    if any(x in p for x in ("pages", "/page/")):
        return "📄 Viewed page" if m == "GET" else "📄 Page action"
    if "webhook" in p:
        return "🔗 Webhook action"
    if "preferences" in p:
        return "⚙️ Changed preference" if m == "POST" else "⚙️ Loaded preferences"
    if "search" in p:
        return "🔍 Searched"
    if any(x in p for x in ("socket.io", "/ws/", "websocket")):
        return "📡 WebSocket (bg)"
    if "admin" in p and m == "GET":
        return "⚙️ Admin (bg)"
    suffix = p.rsplit(".", 1)[-1] if "." in p.split("/")[-1] else ""
    if suffix in ("js", "css", "png", "jpg", "jpeg", "gif", "svg",
                  "woff", "woff2", "ico", "map", "ttf"):
        return "🌐 Static asset (bg)"
    if m == "POST":   return f"📤 POST {path}"
    if m == "PUT":    return f"✏️ PUT {path}"
    if m == "DELETE": return f"🗑 DELETE {path}"
    if m == "PATCH":  return f"✏️ PATCH {path}"
    return f"📥 GET {path}"


# ── Core classification engine ────────────────────────────────────────────────
def _classify_divergence(
    evt: Dict[str, Any],
    config: Dict[str, Any],
) -> Dict[str, str]:
    path          = evt.get("path", "")
    method        = evt.get("method", "GET").upper()
    orig          = str(evt.get("original_status", ""))
    replay        = str(evt.get("replay_status", ""))
    original_tier = evt.get("tier", "INVESTIGATE")

    # 1. Custom rules
    for rule in config.get("custom_rules", []):
        m = rule.get("match", {})
        patterns = m.get("path_patterns", [])
        if patterns and not any(fnmatch.fnmatch(path, p) for p in patterns):
            continue
        methods = [x.upper() for x in m.get("methods", [])]
        if methods and method not in methods:
            continue
        orig_statuses = [str(s) for s in m.get("original_statuses", [])]
        if orig_statuses and orig not in orig_statuses:
            continue
        replay_statuses = [str(s) for s in m.get("replay_statuses", [])]
        if replay_statuses and replay not in replay_statuses:
            continue
        return {
            "tier":           rule.get("tier", original_tier),
            "rule_id":        rule.get("id", "custom"),
            "rule_label":     rule.get("label", "Custom Rule"),
            "reason":         (rule.get("reason") or "").strip(),
            "recommendation": (rule.get("recommendation") or "").strip(),
        }

    # 2. Global noise transitions
    for trans in config.get("global_noise", {}).get("status_transitions", []):
        if str(trans.get("from", "")) == orig and str(trans.get("to", "")) == replay:
            return {
                "tier":           "EXPECTED",
                "rule_id":        f"global_noise:{trans['from']}->{trans['to']}",
                "rule_label":     f"Global Noise: {trans['from']}→{trans['to']}",
                "reason":         (trans.get("reason") or "").strip(),
                "recommendation": (trans.get("recommendation") or "").strip(),
            }

    # 3. Fallback — no rule matched
    return {
        "tier":           original_tier,
        "rule_id":        "no_match",
        "rule_label":     "No Rule Matched",
        "reason":         "",
        "recommendation": "",
    }


def _auth_tag_str(auth_mode: str, auth_active: bool) -> str:
    if auth_mode == "jwt":    return "with JWT 🔑"
    if auth_mode == "cookie": return "with Session 🍪"
    if auth_active:           return "authenticated 🔐"
    return "no auth ⚠"


# ── Build template context ────────────────────────────────────────────────────
def build_ctx(report: Dict[str, Any], config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    if config is None:
        config = report.get("config", {})

    raw      = report.get("divergences") or {}
    expected = list(raw.get("expected", []))
    invest   = list(raw.get("investigate", []))
    critical = list(raw.get("critical", []))

    if not any([expected, invest, critical]):
        for d in report.get("divergence_analysis", {}).get("details", []):
            t = d.get("tier", "INVESTIGATE")
            if t == "EXPECTED":   expected.append(d)
            elif t == "CRITICAL": critical.append(d)
            else:                 invest.append(d)

    summary  = report.get("summary", {})
    total    = summary.get("total_events", 0)
    duration = summary.get("duration_seconds", 0)
    avg_ms   = report.get("performance", {}).get("avg_response_time_ms", 0)
    rid      = report.get("replay_id", "unknown")
    ts       = report.get("timestamp", "")

    auth_mode   = summary.get("auth_mode", "none")
    auth_active = summary.get("auth_was_active", False)
    if not auth_active and summary.get("jwt_token_injected", False):
        auth_mode   = "jwt"
        auth_active = True

    def reclassify_list(events: list, engine_tier: str) -> Tuple[list, list, list]:
        _exp, _inv, _crit = [], [], []
        for evt in events:
            evt = dict(evt)
            evt["tier"] = engine_tier
            cl = _classify_divergence(evt, config)
            evt.update({
                "tier":                          cl["tier"],
                "rule_id":                       cl["rule_id"],
                "rule_label":                    cl["rule_label"],
                "classification_reason":         cl["reason"],
                "classification_recommendation": cl["recommendation"],
            })
            t = cl["tier"]
            if t == "EXPECTED":   _exp.append(evt)
            elif t == "CRITICAL": _crit.append(evt)
            else:                 _inv.append(evt)
        return _exp, _inv, _crit

    exp_from_exp, inv_from_exp, crit_from_exp = reclassify_list(expected,  "EXPECTED")
    exp_from_inv, inv_from_inv, crit_from_inv = reclassify_list(invest,    "INVESTIGATE")
    exp_from_crt, inv_from_crt, crit_from_crt = reclassify_list(critical,  "CRITICAL")

    expected_final = exp_from_exp + exp_from_inv + exp_from_crt
    invest_final   = inv_from_exp + inv_from_inv + inv_from_crt
    critical_final = crit_from_exp + crit_from_inv + crit_from_crt

    reclassified_lookup = {
        evt.get("event_id", ""): evt
        for evt in expected_final + invest_final + critical_final
    }

    ne, ni, nc = len(expected_final), len(invest_final), len(critical_final)
    n_exact = total - ne - ni - nc
    rate    = round((n_exact + ne) / total * 100, 1) if total > 0 else 100.0

    # ── Verdict logic ─────────────────────────────────────────────────────────
    # nc_unclassified = CRITICAL items with NO matching rule (genuine unknowns)
    # Classified CRITICAL items (rule_id != "no_match") are explained — not genuine bugs
    nc_unclassified = sum(1 for e in critical_final if e.get("rule_id", "") in ("no_match", ""))
    
    if total == 0:
        verdict, vcol, vtext = "INVALID", "#6b7280", "No traffic found to replay."
        rate_col = "#6b7280"
        rate = 0.0
    elif rate >= 95.0 and nc_unclassified == 0:
        verdict, vcol, vtext = "PASS",   "#16a34a", "High Reproducibility. Approved."
        rate_col = "#16a34a"
    elif rate >= 95.0 and nc_unclassified > 0:
        verdict, vcol, vtext = "REVIEW", "#d97706", "Unclassified divergences found. Review before promoting."
        rate_col = "#d97706"
    elif rate >= 80.0:
        verdict, vcol, vtext = "REVIEW", "#d97706", "Acceptable reproducibility. Check divergences."
        rate_col = "#d97706"
    else:
        verdict, vcol, vtext = "FAIL",   "#dc2626", "Low reproducibility. Do not ship."
        rate_col = "#dc2626"

    # ── Final statement ───────────────────────────────────────────────────────
    if total == 0:
        final_stmt = "<strong>0 requests found.</strong> The selected timeframe contains no logs to replay. Please record new traffic."
    elif nc_unclassified == 0 and ni == 0:
        final_stmt = (
            f"<strong>{n_exact} request{'s' if n_exact != 1 else ''} reproduced exactly.</strong> "
            + (f"{ne} divergence{'s' if ne != 1 else ''} classified as expected noise — excluded from repro rate. " if ne > 0 else "")
            + (f"{nc} divergence{'s' if nc != 1 else ''} classified with a known cause and rule. " if nc > 0 else "")
            + "No unclassified mismatches. <strong>Clear to promote.</strong>"
        )
    elif nc_unclassified == 0:
        final_stmt = (
            f"<strong>{rate}% Reproducibility.</strong> "
            f"There are {ni} item{'s' if ni != 1 else ''} that require manual review. "
            "No unclassified mismatches detected. "
            "<strong>Review the investigation tab, then promote.</strong>"
        )
    elif rate >= 95.0:
        final_stmt = (
            f"<strong>{rate}% Reproducibility Achieved.</strong> "
            f"The application is highly deterministic, but {nc_unclassified} divergence{'s have' if nc_unclassified != 1 else ' has'} "
            "no matching rule in <code>divergence_config.yaml</code>. "
            "These may be expected state drift that needs a new rule, or genuine non-determinism. "
            "<strong>Review the Genuine Bugs tab. Add a rule if expected, leave if it is a real bug.</strong>"
        )
    else:
        final_stmt = (
            f"<strong>Only {rate}% Reproducibility.</strong> "
            f"{nc_unclassified} unclassified mismatch{'es' if nc_unclassified != 1 else ''} found. "
            "The application state is highly volatile or real bugs exist. "
            "<strong>Do not ship until resolved.</strong>"
        )

    # ── Investigation panel intro ─────────────────────────────────────────────
    if ni > 0:
        inv_rules  = list(dict.fromkeys(d.get("rule_label", "No Rule Matched") for d in invest_final))
        rules_text = ", ".join(f"<em>{r}</em>" for r in inv_rules[:3])
        if len(inv_rules) > 3:
            rules_text += f", +{len(inv_rules) - 3} more"
        invest_intro = (
            f"<strong>{ni} item{'s' if ni != 1 else ''} to investigate.</strong> "
            f"Matched rule{'s' if len(inv_rules) > 1 else ''}: {rules_text}. "
            "Each card below shows the exact rule that matched and the recommended action."
        )
    else:
        invest_intro = "<strong>Nothing to investigate.</strong> All divergences were classified as expected noise."

    def tag(evt: Dict[str, Any], diverged: bool = False) -> Dict[str, Any]:
        evt = dict(evt)
        o = evt.get("original_status")
        r = evt.get("replay_status")
        tier = evt.get("tier", "")

        evt_auth_mode   = evt.get("auth_mode", auth_mode)
        evt_auth_active = evt.get("auth_was_active", evt.get("jwt_was_active", auth_active))

        ol, oc = _status_info(o)
        rl, rc = _status_info(r)
        if not diverged:
            rc = "#16a34a"

        atag = _auth_tag_str(evt_auth_mode, evt_auth_active)
        if o == r:
            engine_txt = f"Replayed {evt.get('method','')} {evt.get('path','')} ({atag}) → ✅ {r}"
        else:
            engine_txt = f"Replayed {evt.get('method','')} {evt.get('path','')} ({atag}) → ❌ got {r}, expected {o}"

        return {
            **evt,
            "diverged":                      diverged,
            "tier":                          tier,
            "tier_color":                    _TIER_COLORS.get(tier, "#aaa"),
            "method_color":                  _METHOD_COLORS.get(str(evt.get("method", "")).upper(), "#aaa"),
            "o_label": ol, "o_color": oc,
            "r_label": rl, "r_color": rc,
            "user_action":                   _what_user_did(evt.get("method", "GET"), evt.get("path", "/")),
            "engine_action":                 engine_txt,
            "short_id":                      str(evt.get("event_id", ""))[:8],
            "rule_id":                       evt.get("rule_id", ""),
            "rule_label":                    evt.get("rule_label", ""),
            "classification_reason":         evt.get("classification_reason", ""),
            "classification_recommendation": evt.get("classification_recommendation", ""),
        }

    all_evts = report.get("all_events", [])
    session  = []
    if all_evts:
        for e in all_evts:
            eid = e.get("event_id", "")
            if eid in reclassified_lookup:
                session.append(tag(reclassified_lookup[eid], diverged=True))
            else:
                session.append(tag(e, diverged=False))
    else:
        for d in invest_final + critical_final:
            session.append(tag(d, diverged=True))

    if auth_mode == "jwt":
        auth_badge_cls, auth_badge_text = "yes", "✓ JWT"
    elif auth_mode == "cookie":
        auth_badge_cls, auth_badge_text = "yes", "✓ Session Cookie"
    else:
        auth_badge_cls, auth_badge_text = "no", "⚠ no auth"

    auth_notes      = config.get("auth_notes", {})
    mode_note       = auth_notes.get(auth_mode, auth_notes.get("none", {}))
    auth_note_title = mode_note.get("title", "⏱ Auth")
    auth_note_body  = mode_note.get("body", "")

    app_meta = config.get("app", {})
    app_name = app_meta.get("name", "")
    app_desc = app_meta.get("description", "")

    return {
        "rid":              rid,
        "ts":               ts,
        "total":            total,
        "duration":         duration,
        "avg_ms":           avg_ms,
        "auth_mode":        auth_mode,
        "auth_active":      auth_active,
        "auth_badge_cls":   auth_badge_cls,
        "auth_badge_text":  auth_badge_text,
        "auth_note_title":  auth_note_title,
        "auth_note_body":   auth_note_body,
        "app_name":         app_name,
        "app_desc":         app_desc,
        "n_exact":          n_exact,
        "ne":               ne,
        "ni":               ni,
        "nc":               nc,
        "nc_unclassified":  nc_unclassified,
        "rate":             rate,
        "rate_col":         rate_col,
        "verdict":          verdict,
        "vcol":             vcol,
        "vtext":            vtext,
        "final_stmt":       final_stmt,
        "invest_intro":     invest_intro,
        "session":          session,
        "nsession":         len(session),
        "tab_expected":     [tag(d, diverged=True) for d in expected_final],
        "tab_invest":       [tag(d, diverged=True) for d in invest_final],
        "tab_critical":     [tag(d, diverged=True) for d in critical_final],
    }


# ── Jinja2 HTML template ──────────────────────────────────────────────────────
TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>DLTRF{% if app_name %} · {{ app_name }}{% endif %} — {{ rid }}</title>
  <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@400;600;700;800&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Bricolage Grotesque', sans-serif;
      background: #d3d3d3;
      color: #111827;
      line-height: 1.5;
      border-top: 4px solid #2563eb;
    }
    .wrap { max-width: 1060px; margin: 0 auto; padding: 0 28px; }
    section { padding: 44px 0; }
    section + section { border-top: 1px solid #c4c4c4; }
    .sec-label { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.1em; color: #6b7280; margin-bottom: 18px; font-weight: 600; }

    .topbar { background: #f9fafb; border-bottom: 1px solid #e5e7eb; padding: 20px 0; }
    .topbar-inner { display: flex; align-items: center; justify-content: space-between; gap: 16px; flex-wrap: wrap; }
    .brand { display: flex; align-items: baseline; gap: 10px; margin-bottom: 6px; }
    .brand-name { font-size: 1.4rem; font-weight: 800; letter-spacing: 0.06em; color: #111827; }
    .brand-name::before { content: '■'; color: #2563eb; margin-right: 8px; font-size: 0.55em; vertical-align: middle; }
    .brand-sub { font-size: 0.73rem; color: #6b7280; text-transform: uppercase; letter-spacing: 0.04em; }
    .meta { font-size: 0.76rem; color: #6b7280; line-height: 1.7; font-family: 'DM Mono', monospace; }
    .meta strong { color: #374151; font-weight: 500; }
    .mbadge { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 0.7rem; font-weight: 600; margin-left: 6px; }
    .mbadge.yes { background: #dcfce7; color: #16a34a; border: 1px solid #bbf7d0; }
    .mbadge.no  { background: #fef3c7; color: #d97706; border: 1px solid #fde68a; }

    .dl-wrap { position: relative; flex-shrink: 0; }
    .dl-btn { display: flex; align-items: center; gap: 7px; background: #ffffff; border: 1px solid #d1d5db; color: #4b5563; padding: 8px 14px; border-radius: 5px; cursor: pointer; font-size: 0.82rem; font-weight: 600; font-family: 'Bricolage Grotesque', sans-serif; transition: all 0.15s; white-space: nowrap; box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
    .dl-btn:hover { border-color: #2563eb; color: #1d4ed8; background: #eff6ff; }
    .dl-chev { font-size: 0.55rem; margin-left: 2px; display: inline-block; transition: transform 0.15s; }
    .dl-wrap.open .dl-chev { transform: rotate(180deg); }
    .dl-menu { display: none; position: absolute; right: 0; top: calc(100% + 5px); background: #ffffff; border: 1px solid #e5e7eb; border-radius: 6px; min-width: 270px; overflow: hidden; box-shadow: 0 10px 25px -5px rgba(0,0,0,0.1); z-index: 200; }
    .dl-wrap.open .dl-menu { display: block; }
    .dl-opt { display: flex; align-items: flex-start; gap: 11px; padding: 13px 15px; cursor: pointer; border-bottom: 1px solid #f3f4f6; transition: background 0.12s; }
    .dl-opt:last-child { border-bottom: none; }
    .dl-opt:hover { background: #f9fafb; }
    .dl-opt-ico { font-size: 1.1rem; flex-shrink: 0; margin-top: 1px; }
    .dl-opt-title { font-size: 0.84rem; font-weight: 700; color: #111827; margin-bottom: 2px; }
    .dl-opt-desc { font-size: 0.74rem; color: #6b7280; line-height: 1.45; }

    .auth-note { border-left: 4px solid #f59e0b; border-radius: 0 6px 6px 0; padding: 12px 16px; }
    .auth-note.jwt    { background: #fffbeb; }
    .auth-note.cookie { background: #f0fdf4; border-left-color: #22c55e; }
    .auth-note.none   { background: #f9fafb; border-left-color: #9ca3af; }
    .auth-note-title { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 700; margin-bottom: 5px; }
    .auth-note.jwt    .auth-note-title { color: #d97706; }
    .auth-note.cookie .auth-note-title { color: #16a34a; }
    .auth-note.none   .auth-note-title { color: #4b5563; }
    .auth-note-text { font-size: 0.83rem; line-height: 1.6; }
    .auth-note.jwt    .auth-note-text { color: #92400e; }
    .auth-note.cookie .auth-note-text { color: #166534; }
    .auth-note.none   .auth-note-text { color: #4b5563; }
    .auth-note-text code { padding: 0 4px; border-radius: 3px; font-family: 'DM Mono', monospace; font-size: 0.8em; background: rgba(0,0,0,0.05); color: #111827; }

    .explainer { background: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 22px 26px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
    .explainer h2 { font-size: 1.1rem; font-weight: 700; margin-bottom: 10px; color: #111827; }
    .explainer p { font-size: 0.88rem; color: #4b5563; line-height: 1.75; margin-bottom: 10px; }
    .explainer p:last-child { margin-bottom: 0; }
    .explainer strong { color: #111827; }

    .glossary { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 11px; }
    .gc { background: #ffffff; border: 1px solid #e5e7eb; border-radius: 6px; padding: 14px 16px; box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
    .gc-val  { font-size: 1.35rem; font-weight: 800; font-family: 'DM Mono', monospace; margin-bottom: 3px; }
    .gc-term { font-size: 0.72rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.04em; margin-bottom: 4px; }
    .gc-def  { font-size: 0.78rem; color: #6b7280; line-height: 1.5; }

    .verdict { border-radius: 10px; padding: 32px 36px; background: #ffffff; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
    .verdict.pass   { border: 2px solid #22c55e; }
    .verdict.review { border: 2px solid #f59e0b; }
    .verdict.fail   { border: 2px solid #ef4444; border-left: 8px solid #ef4444; }
    .v-pct  { font-size: 3rem; font-weight: 800; font-family: 'DM Mono', monospace; line-height: 1; margin-bottom: 6px; }
    .v-rule { width: 60px; height: 2px; margin: 14px 0; }
    .v-head { font-size: 2.2rem; font-weight: 800; line-height: 1; margin-bottom: 8px; }
    .v-sub  { font-size: 0.92rem; color: #6b7280; }
    .bkdn   { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-top: 24px; }
    .bk     { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 16px; }
    .bk-val   { font-size: 1.7rem; font-weight: 800; font-family: 'DM Mono', monospace; margin-bottom: 4px; }
    .bk-label { font-size: 0.74rem; font-weight: 700; margin-bottom: 5px; }
    .bk-desc  { font-size: 0.78rem; color: #6b7280; line-height: 1.45; }
    .final-stmt { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 7px; padding: 18px 22px; margin-top: 22px; }
    .final-stmt p { font-size: 0.88rem; line-height: 1.75; color: #374151; }
    .final-stmt strong { color: #111827; }
    .v-actions { margin-top: 20px; display: flex; align-items: center; gap: 16px; flex-wrap: wrap; }
    .v-btn { display: inline-block; padding: 10px 22px; border-radius: 5px; text-decoration: none; font-weight: 700; font-size: 0.88rem; box-shadow: 0 1px 2px rgba(0,0,0,0.05); }
    .v-btn.pass   { background: #22c55e; color: #ffffff; }
    .v-btn.review { background: #f59e0b; color: #ffffff; }
    .v-btn.fail   { background: #ef4444; color: #ffffff; }
    .v-meta { font-size: 0.7rem; color: #6b7280; font-family: 'DM Mono', monospace; line-height: 1.7; }

    .tabs { display: flex; flex-wrap: wrap; border-bottom: 1px solid #e5e7eb; margin-bottom: 24px; }
    .tab { background: transparent; border: none; color: #6b7280; padding: 11px 18px; cursor: pointer; font-size: 0.85rem; font-weight: 600; font-family: 'Bricolage Grotesque', sans-serif; display: flex; align-items: center; gap: 7px; border-bottom: 2px solid transparent; margin-bottom: -1px; white-space: nowrap; transition: color 0.15s; }
    .tab:hover { color: #374151; }
    .tab.active { color: #1d4ed8; border-bottom-color: #2563eb; }
    .tab-ct { padding: 1px 6px; border-radius: 9px; font-size: 0.67rem; font-weight: 700; background: #e5e7eb; color: #4b5563; }
    .tab.active .tab-ct { background: #dbeafe; color: #1d4ed8; }
    .panel { display: none; }
    .panel.active { display: block; }
    .p-intro { background: #eff6ff; border-left: 3px solid #3b82f6; padding: 12px 16px; margin-bottom: 20px; font-size: 0.84rem; color: #1e40af; line-height: 1.6; border-radius: 0 5px 5px 0; }
    .p-intro strong { color: #1e3a8a; }

    .mf { display: flex; gap: 7px; flex-wrap: wrap; align-items: center; margin-bottom: 18px; }
    .mf-lbl { font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; margin-right: 4px; }
    .mf-btn { background: #ffffff; border: 1px solid #d1d5db; color: #4b5563; padding: 5px 11px; border-radius: 4px; cursor: pointer; font-size: 0.78rem; font-weight: 600; font-family: 'DM Mono', monospace; transition: all 0.12s; }
    .mf-btn:hover { border-color: #2563eb; color: #1d4ed8; }
    .mf-btn.active { background: #eff6ff; border-color: #2563eb; color: #1d4ed8; }
    .mf-shown { color: #6b7280; font-size: 0.74rem; }

    .evt { background: #ffffff; border: 1px solid #e5e7eb; border-radius: 7px; padding: 18px; margin-bottom: 11px; box-shadow: 0 1px 2px rgba(0,0,0,0.03); }
    .evt.diverged { box-shadow: 0 2px 5px rgba(0,0,0,0.06); border-left: 3px solid; }
    .evt.diverged.expected    { border-left-color: #22c55e; }
    .evt.diverged.investigate { border-left-color: #f59e0b; }
    .evt.diverged.critical    { border-left-color: #ef4444; }
    .evt-hdr { display: flex; align-items: center; gap: 9px; margin-bottom: 14px; flex-wrap: wrap; }
    .meth { font-family: 'DM Mono', monospace; font-weight: 700; font-size: 0.78rem; padding: 3px 8px; border-radius: 3px; }
    .meth.GET    { background: #dbeafe; color: #1d4ed8; }
    .meth.POST   { background: #dcfce7; color: #15803d; }
    .meth.PUT    { background: #fef3c7; color: #b45309; }
    .meth.DELETE { background: #fee2e2; color: #b91c1c; }
    .meth.PATCH  { background: #f3e8ff; color: #7e22ce; }
    .evt-path { font-family: 'DM Mono', monospace; font-size: 0.78rem; color: #111827; flex: 1; word-break: break-all; min-width: 0; }
    .tier-bdg { padding: 2px 7px; border-radius: 3px; font-size: 0.65rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.04em; flex-shrink: 0; }
    .tier-bdg.EXPECTED    { background: #f0fdf4; color: #16a34a; border: 1px solid #bbf7d0; }
    .tier-bdg.INVESTIGATE { background: #fffbeb; color: #d97706; border: 1px solid #fde68a; }
    .tier-bdg.CRITICAL    { background: #fef2f2; color: #dc2626; border: 1px solid #fecaca; }
    .tier-bdg.ok          { background: #f8fafc; color: #0f766e; border: 1px solid #ccfbf1; }
    .evt-id { font-family: 'DM Mono', monospace; font-size: 0.65rem; color: #6b7280; background: #f3f4f6; padding: 2px 6px; border-radius: 3px; flex-shrink: 0; }
    .evt-acts { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 10px; }
    .abox { background: #f9fafb; border: 1px solid #f3f4f6; border-radius: 5px; padding: 11px 13px; min-width: 0; overflow: hidden; }
    .albl { font-size: 0.63rem; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; margin-bottom: 5px; }
    .atxt { font-size: 0.84rem; color: #111827; line-height: 1.45; word-break: break-all; overflow-wrap: break-word; }
    .evt-sts { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
    .stbox { background: #f9fafb; border: 1px solid #f3f4f6; border-radius: 5px; padding: 11px 13px; }
    .stlbl { font-size: 0.6rem; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; margin-bottom: 4px; }
    .stcode { font-size: 1.6rem; font-weight: 800; font-family: 'DM Mono', monospace; line-height: 1; margin-bottom: 2px; }
    .sttxt  { font-size: 0.68rem; color: #4b5563; }

    .clf-box { margin-top: 10px; border-radius: 6px; overflow: hidden; border: 1px solid; }
    .clf-box.expected    { border-color: #bbf7d0; }
    .clf-box.investigate { border-color: #fde68a; }
    .clf-box.critical    { border-color: #fecaca; }
    .clf-hdr { display: flex; align-items: center; gap: 8px; padding: 8px 13px; font-size: 0.65rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }
    .clf-box.expected    .clf-hdr { background: #f0fdf4; color: #15803d; }
    .clf-box.investigate .clf-hdr { background: #fffbeb; color: #b45309; }
    .clf-box.critical    .clf-hdr { background: #fef2f2; color: #b91c1c; }
    .clf-rule-id { font-family: 'DM Mono', monospace; padding: 1px 5px; border-radius: 3px; font-size: 0.7rem; font-weight: 500; }
    .clf-box.expected    .clf-rule-id { background: #dcfce7; color: #166534; }
    .clf-box.investigate .clf-rule-id { background: #fef3c7; color: #92400e; }
    .clf-box.critical    .clf-rule-id { background: #fee2e2; color: #991b1b; }
    .clf-body { padding: 11px 13px; background: #ffffff; }
    .clf-reason { font-size: 0.82rem; color: #374151; line-height: 1.6; margin-bottom: 8px; }
    .clf-rec { font-size: 0.8rem; color: #4b5563; line-height: 1.55; padding-top: 8px; border-top: 1px solid #f3f4f6; }
    .clf-rec::before { content: '💡 '; }
    .clf-nomatch { margin-top: 10px; background: #f9fafb; border: 1px dashed #cbd5e1; border-radius: 5px; padding: 10px 13px; }
    .clf-nomatch-lbl { font-size: 0.63rem; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; margin-bottom: 4px; }
    .clf-nomatch-txt { font-family: 'DM Mono', monospace; font-size: 0.7rem; color: #475569; }
    .empty { text-align: center; padding: 48px 20px; color: #6b7280; font-size: 0.95rem; }

    @media (max-width: 720px) {
      .bkdn, .evt-acts, .evt-sts { grid-template-columns: 1fr; }
      .v-pct { font-size: 2.2rem; }
      .v-head { font-size: 1.6rem; }
      .topbar-inner { flex-direction: column; align-items: flex-start; }
      .glossary { grid-template-columns: 1fr 1fr; }
    }
  </style>
</head>
<body>

<div class="topbar">
  <div class="wrap">
    <div class="topbar-inner">
      <div>
        <div class="brand">
          <div class="brand-name">DLTRF{% if app_name %} · {{ app_name }}{% endif %}</div>
          <div class="brand-sub">Replay Report</div>
        </div>
        <div class="meta">
          <strong>{{ rid }}</strong> &middot; {{ ts }}<br>
          {{ total }} events &middot; {{ duration }}s &middot; {{ rate }}% repro
          <span class="mbadge {{ auth_badge_cls }}">{{ auth_badge_text }}</span>
        </div>
      </div>
      <div class="dl-wrap" id="dlWrap">
        <button class="dl-btn" onclick="toggleDl(event)" type="button">
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" style="flex-shrink:0">
            <path d="M7 1v7M4.5 6l2.5 2.5L9.5 6M1.5 11.5h11" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          Download <span class="dl-chev">▼</span>
        </button>
        <div class="dl-menu" id="dlMenu">
          <div class="dl-opt" onclick="doDownload('full')" role="button">
            <div class="dl-opt-ico">📋</div>
            <div><div class="dl-opt-title">Full Report</div><div class="dl-opt-desc">All {{ nsession }} session events — every request log included.</div></div>
          </div>
          <div class="dl-opt" onclick="doDownload('summary')" role="button">
            <div class="dl-opt-ico">📊</div>
            <div><div class="dl-opt-title">Summary Only</div><div class="dl-opt-desc">Verdict + metrics, no request logs. Good for sharing upwards.</div></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div style="padding: 16px 0 0">
  <div class="wrap">
    <div class="auth-note {{ auth_mode }}">
      <div class="auth-note-title">{{ auth_note_title }}</div>
      <div class="auth-note-text">{{ auth_note_body }}</div>
    </div>
  </div>
</div>

<section>
  <div class="wrap">
    <div class="sec-label">What is this</div>
    <div class="explainer">
      <h2>DLTRF — Deterministic Log Test Replay Framework</h2>
      <p>Records every HTTP request your browser makes during a session, then <strong>replays those exact requests</strong> and compares the responses. If the server returns the same thing, the app is deterministic. If not, something changed.</p>
      <p>Divergences are classified by rules in <code>divergence_config.yaml</code>. Every event card shows the exact rule that matched and the reasoning — so you never have to guess why something was flagged.{% if app_desc %} <strong>App:</strong> {{ app_desc }}{% endif %}</p>
    </div>
  </div>
</section>

<section style="padding-top: 36px">
  <div class="wrap">
    <div class="sec-label">Numbers</div>
    <div class="glossary">
      <div class="gc">
        <div class="gc-val" style="color:#2563eb">{{ total }}</div>
        <div class="gc-term" style="color:#2563eb">Events replayed</div>
        <div class="gc-def">HTTP requests re-executed. One event = one request your browser made.</div>
      </div>
      <div class="gc">
        <div class="gc-val" style="color:{{ rate_col }}">{{ rate }}%</div>
        <div class="gc-term" style="color:{{ rate_col }}">Repro rate</div>
        <div class="gc-def">Requests that got the same response. Expected noise excluded — honest number.</div>
      </div>
      <div class="gc">
        <div class="gc-val" style="color:#16a34a">{{ n_exact }}</div>
        <div class="gc-term" style="color:#16a34a">Exact matches</div>
        <div class="gc-def">Same status code both times. Fully deterministic.</div>
      </div>
      <div class="gc">
        <div class="gc-val" style="color:#22c55e">{{ ne }}</div>
        <div class="gc-term" style="color:#22c55e">Expected noise</div>
        <div class="gc-def">Classified as known behaviour by a config rule. Not bugs — excluded from repro rate.</div>
      </div>
      <div class="gc">
        <div class="gc-val" style="color:#d97706">{{ ni }}</div>
        <div class="gc-term" style="color:#d97706">Needs a look</div>
        <div class="gc-def">Diverged for a reviewable reason. Check the matched rule in each card.</div>
      </div>
      <div class="gc">
        <div class="gc-val" style="color:{% if nc_unclassified > 0 %}#dc2626{% else %}#16a34a{% endif %}">{{ nc_unclassified }}</div>
        <div class="gc-term" style="color:{% if nc_unclassified > 0 %}#dc2626{% else %}#16a34a{% endif %}">Genuine bugs</div>
        <div class="gc-def">Different response, same input, NO matching rule. Real unknowns — add a rule or fix the bug.</div>
      </div>
      <div class="gc">
        <div class="gc-val" style="color:#4b5563">{{ avg_ms|int }}ms</div>
        <div class="gc-term">Avg response</div>
        <div class="gc-def">Per request. Useful for catching perf regressions between sessions.</div>
      </div>
      <div class="gc">
        <div class="gc-val" style="color:#4b5563">{{ duration }}s</div>
        <div class="gc-term">Total time</div>
        <div class="gc-def">Full replay duration including network + comparison + report gen.</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="sec-label">Final verdict — session replay complete</div>
    {% if verdict == "PASS" %}
    <div class="verdict pass">
      <div class="v-pct" style="color:#16a34a">{{ rate }}%</div>
      <div class="v-rule" style="background:#16a34a"></div>
      <div class="v-head" style="color:#16a34a">PASS</div>
      <div class="v-sub">{{ vtext }}</div>
      <div class="bkdn">
        <div class="bk" style="border-left:2px solid #16a34a">
          <div class="bk-val" style="color:#16a34a">{{ n_exact }}</div>
          <div class="bk-label" style="color:#16a34a">What worked</div>
          <div class="bk-desc">{{ n_exact }} exact matches. App is deterministic.</div>
        </div>
        <div class="bk" style="border-left:2px solid #22c55e">
          <div class="bk-val" style="color:#22c55e">{{ ne }}</div>
          <div class="bk-label" style="color:#22c55e">Expected noise</div>
          <div class="bk-desc">{% if ne > 0 %}Classified by config rules. Excluded from rate.{% else %}None detected.{% endif %}</div>
        </div>
        <div class="bk" style="border-left:2px solid #16a34a">
          <div class="bk-val" style="color:#16a34a">0</div>
          <div class="bk-label" style="color:#16a34a">Genuine bugs</div>
          <div class="bk-desc">No unclassified mismatches found.</div>
        </div>
      </div>
      <div class="final-stmt"><p>{{ final_stmt }}</p></div>
      <div class="v-actions">
        <a class="v-btn pass" href="#">✓ Promote to next environment</a>
        <div class="v-meta">{{ rid }}<br>{{ ts }}<br>{{ total }} events · {{ duration }}s · {{ rate }}%</div>
      </div>
    </div>
    {% elif verdict == "REVIEW" %}
    <div class="verdict review">
      <div class="v-head" style="color:#d97706">REVIEW</div>
      <div class="v-sub">{{ vtext }}</div>
      <div class="bkdn">
        <div class="bk" style="border-left:2px solid #16a34a">
          <div class="bk-val" style="color:#16a34a">{{ n_exact }}</div>
          <div class="bk-label" style="color:#16a34a">What worked</div>
          <div class="bk-desc">{{ n_exact }} exact. {{ ni }} investigation item{% if ni != 1 %}s{% endif %}.</div>
        </div>
        <div class="bk" style="border-left:2px solid #22c55e">
          <div class="bk-val" style="color:#22c55e">{{ ne }}</div>
          <div class="bk-label" style="color:#22c55e">Expected noise</div>
          <div class="bk-desc">{% if ne > 0 %}Classified by config rules. Excluded.{% else %}None.{% endif %}</div>
        </div>
        <div class="bk" style="border-left:2px solid #f59e0b">
          <div class="bk-val" style="color:#d97706">{{ nc_unclassified }}</div>
          <div class="bk-label" style="color:#d97706">Unclassified</div>
          <div class="bk-desc">{% if nc_unclassified > 0 %}No matching rule. Review before promoting.{% else %}None.{% endif %}</div>
        </div>
      </div>
      <div class="final-stmt"><p>{{ final_stmt }}</p></div>
      <div class="v-actions">
        <a class="v-btn review" href="#">⚠ Review before promoting</a>
        <div class="v-meta">{{ rid }}<br>{{ ts }}</div>
      </div>
    </div>
    {% else %}
    <div class="verdict fail">
      <div class="v-pct" style="color:#dc2626">{{ nc_unclassified }}</div>
      <div class="v-rule" style="background:#dc2626"></div>
      <div class="v-head" style="color:#dc2626">FAIL</div>
      <div class="v-sub">{{ vtext }}</div>
      <div class="bkdn">
        <div class="bk" style="border-left:2px solid #16a34a">
          <div class="bk-val" style="color:#16a34a">{{ n_exact }}</div>
          <div class="bk-label" style="color:#16a34a">What worked</div>
          <div class="bk-desc">{{ n_exact }} reproduced fine.</div>
        </div>
        <div class="bk" style="border-left:2px solid #22c55e">
          <div class="bk-val" style="color:#22c55e">{{ ne }}</div>
          <div class="bk-label" style="color:#22c55e">Expected noise</div>
          <div class="bk-desc">{% if ne > 0 %}Classified by config rules.{% else %}None.{% endif %}</div>
        </div>
        <div class="bk" style="border-left:2px solid #dc2626">
          <div class="bk-val" style="color:#dc2626">{{ nc_unclassified }}</div>
          <div class="bk-label" style="color:#dc2626">Genuine bugs</div>
          <div class="bk-desc">No matching rule. Investigate before shipping.</div>
        </div>
      </div>
      <div class="final-stmt"><p>{{ final_stmt }}</p></div>
      <div class="v-actions">
        <a class="v-btn fail" href="#">✕ Do not promote</a>
        <div class="v-meta">{{ rid }}<br>{{ ts }}</div>
      </div>
    </div>
    {% endif %}
  </div>
</section>

<section id="dev-detail" style="padding-bottom: 64px">
  <div class="wrap">
    <div class="sec-label">Developer detail</div>
    <p style="color:#4b5563; font-size:.84rem; margin-bottom:22px; line-height:1.6">Per-request breakdown. Every diverged event shows which config rule classified it and why.</p>
    <div class="tabs">
      <button class="tab active" onclick="showTab('session',this)">👤 Your Session <span class="tab-ct">{{ nsession }}</span></button>
      <button class="tab" onclick="showTab('expected',this)">🟢 Expected Noise <span class="tab-ct">{{ ne }}</span></button>
      <button class="tab" onclick="showTab('investigate',this)">🟠 Needs Investigation <span class="tab-ct">{{ ni }}</span></button>
      <button class="tab" onclick="showTab('critical',this)">🔴 Genuine Bugs <span class="tab-ct">{{ nc }}</span></button>
    </div>

    {% macro ecard(evt) %}
    <div class="evt evt-card {% if evt.diverged %}diverged {{ evt.tier|lower }}{% endif %}" data-method="{{ evt.method }}">
      <div class="evt-hdr">
        <span class="meth {{ evt.method }}">{{ evt.method }}</span>
        <span class="evt-path">{{ evt.path }}</span>
        {% if evt.diverged %}
          <span class="tier-bdg {{ evt.tier }}">{{ evt.tier }}</span>
        {% else %}
          <span class="tier-bdg ok">✓ REPRODUCED</span>
        {% endif %}
        <span class="evt-id">#{{ evt.short_id }}</span>
      </div>
      <div class="evt-acts">
        <div class="abox">
          <div class="albl">👤 What you did</div>
          <div class="atxt">{{ evt.user_action }}</div>
        </div>
        <div class="abox">
          <div class="albl">🤖 What Replay Engine did</div>
          <div class="atxt">{{ evt.engine_action }}</div>
        </div>
      </div>
      <div class="evt-sts">
        <div class="stbox">
          <div class="stlbl">📹 Recorded response</div>
          <div class="stcode" style="color:{{ evt.o_color }}">{{ evt.original_status or "?" }}</div>
          <div class="sttxt">{{ evt.o_label }}</div>
        </div>
        <div class="stbox">
          <div class="stlbl">🔄 Replay response</div>
          <div class="stcode" style="color:{{ evt.r_color }}">{{ evt.replay_status or "?" }}</div>
          <div class="sttxt">{{ evt.r_label }}{% if not evt.diverged %} ✓ identical{% endif %}</div>
        </div>
      </div>
      {% if evt.diverged %}
        {% if evt.rule_id and evt.rule_id != "no_match" %}
          <div class="clf-box {{ evt.tier|lower }}">
            <div class="clf-hdr">
              📋 Classification
              <span class="clf-rule-id">{{ evt.rule_id }}</span>
              — {{ evt.rule_label }}
            </div>
            <div class="clf-body">
              {% if evt.classification_reason %}<div class="clf-reason">{{ evt.classification_reason }}</div>{% endif %}
              {% if evt.classification_recommendation %}<div class="clf-rec">{{ evt.classification_recommendation }}</div>{% endif %}
            </div>
          </div>
        {% else %}
          <div class="clf-nomatch">
            <div class="clf-nomatch-lbl">⚠ No rule matched — unclassified divergence</div>
            <div class="clf-nomatch-txt">{{ evt.original_status }} → {{ evt.replay_status }}{% if evt.diff_summary %} · {{ evt.diff_summary }}{% endif %}</div>
          </div>
          <div style="margin-top:6px; font-size:0.74rem; color:#6b7280; line-height:1.55; padding: 0 2px">
            No matching rule in <code style="font-family:'DM Mono',monospace;font-size:0.8em">divergence_config.yaml</code>.
            If this is expected behaviour, add a <code style="font-family:'DM Mono',monospace;font-size:0.8em">custom_rule</code> to classify it.
            If it is a real bug, leave it — it will remain in the Genuine Bugs tab.
          </div>
        {% endif %}
      {% endif %}
    </div>
    {% endmacro %}

    <div id="panel-session" class="panel active">
      <div class="p-intro">
        All {{ nsession }} requests. Green badge = exact match. Coloured left border = diverged.
        {% if auth_mode == "jwt" %}<strong>JWT was injected on every authenticated request.</strong>
        {% elif auth_mode == "cookie" %}<strong>Session cookie was injected on every request.</strong>
        {% else %}<strong>No auth detected — see the auth note above.</strong>{% endif %}
      </div>
      <div class="mf">
        <span class="mf-lbl">Filter:</span>
        <button class="mf-btn active" id="mf-ALL"    onclick="filterM('ALL',this)">All ({{ nsession }})</button>
        <button class="mf-btn"        id="mf-GET"    onclick="filterM('GET',this)">GET <span id="cnt-GET"></span></button>
        <button class="mf-btn"        id="mf-POST"   onclick="filterM('POST',this)">POST <span id="cnt-POST"></span></button>
        <button class="mf-btn"        id="mf-PUT"    onclick="filterM('PUT',this)">PUT <span id="cnt-PUT"></span></button>
        <button class="mf-btn"        id="mf-DELETE" onclick="filterM('DELETE',this)">DELETE <span id="cnt-DELETE"></span></button>
        <span class="mf-shown" id="mf-shown"></span>
      </div>
      <div id="session-cards">
        {% if session %}{% for e in session %}{{ ecard(e) }}{% endfor %}
        {% else %}<div class="empty">✓ All reproduced</div>{% endif %}
      </div>
    </div>

    <div id="panel-expected" class="panel">
      <div class="p-intro">
        <strong>Not bugs.</strong> Every item here was classified as expected noise by a rule in
        <code>divergence_config.yaml</code>. {{ ne }} event{% if ne != 1 %}s{% endif %} excluded from repro rate.
      </div>
      {% if tab_expected %}{% for e in tab_expected %}{{ ecard(e) }}{% endfor %}
      {% else %}<div class="empty">None</div>{% endif %}
    </div>

    <div id="panel-investigate" class="panel">
      <div class="p-intro">{{ invest_intro }}</div>
      {% if tab_invest %}{% for e in tab_invest %}{{ ecard(e) }}{% endfor %}
      {% else %}<div class="empty">✓ Nothing to investigate</div>{% endif %}
    </div>

    <div id="panel-critical" class="panel">
      <div class="p-intro">
        <strong>Divergences in this tab</strong> — same request, different response.
        Items with a rule card are <em>classified</em> (the cause is known and explained).
        Items showing "No rule matched" are <em>genuine unknowns</em> — add a rule if expected, or fix the bug.
      </div>
      {% if tab_critical %}{% for e in tab_critical %}{{ ecard(e) }}{% endfor %}
      {% else %}<div class="empty">✓ Zero genuine bugs</div>{% endif %}
    </div>
  </div>
</section>

<script>
function showTab(id, btn) {
  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  document.getElementById('panel-' + id).classList.add('active');
  btn.classList.add('active');
}
function filterM(method, btn) {
  ['ALL','GET','POST','PUT','DELETE'].forEach(m => {
    var b = document.getElementById('mf-' + m);
    if (b) b.classList.toggle('active', m === method);
  });
  var cards = document.querySelectorAll('#session-cards .evt-card'), shown = 0;
  cards.forEach(c => {
    var vis = method === 'ALL' || c.getAttribute('data-method') === method;
    c.style.display = vis ? '' : 'none';
    if (vis) shown++;
  });
  var el = document.getElementById('mf-shown');
  if (el) el.textContent = method === 'ALL' ? '' : shown + ' shown';
}
document.addEventListener('DOMContentLoaded', function() {
  ['GET','POST','PUT','DELETE'].forEach(function(m) {
    var n = document.querySelectorAll('#session-cards .evt-card[data-method="' + m + '"]').length;
    var el = document.getElementById('cnt-' + m);
    if (el) el.textContent = '(' + n + ')';
    if (n === 0 && document.getElementById('mf-' + m))
      document.getElementById('mf-' + m).style.display = 'none';
  });
});
function toggleDl(e) {
  e.stopPropagation();
  document.getElementById('dlWrap').classList.toggle('open');
}
document.addEventListener('click', function() {
  var w = document.getElementById('dlWrap');
  if (w) w.classList.remove('open');
});
function doDownload(mode) {
  document.getElementById('dlWrap').classList.remove('open');
  var html, filename;
  if (mode === 'full') {
    html = '<!DOCTYPE html>\n' + document.documentElement.outerHTML;
    filename = 'dltrf-full-{{ rid }}.html';
  } else {
    var clone = document.documentElement.cloneNode(true);
    var sec = clone.querySelector('#dev-detail');
    if (sec) sec.remove();
    clone.querySelectorAll('script').forEach(s => s.remove());
    var verdict = clone.querySelector('.verdict');
    if (verdict) {
      var note = document.createElement('div');
      note.style.cssText = 'background:#f9fafb;border:1px solid #e5e7eb;border-radius:6px;padding:12px 16px;margin-top:16px;font-size:0.74rem;color:#4b5563;font-family:DM Mono,monospace';
      note.textContent = 'Request logs excluded. Download full report for per-request detail.';
      verdict.parentNode.insertBefore(note, verdict.nextSibling);
    }
    html = '<!DOCTYPE html>\n' + clone.outerHTML;
    filename = 'dltrf-summary-{{ rid }}.html';
  }
  var blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  var url = URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
</script>
</body>
</html>"""


def build_html_report(report: Dict[str, Any], config: Optional[Dict[str, Any]] = None) -> str:
    env = Environment(loader=BaseLoader(), autoescape=False)
    t   = env.from_string(TEMPLATE)
    return t.render(**build_ctx(report, config))