# =============================================================================
#  DLTRF - Ansible Inventory
#  File: ansible/inventory.ini
# =============================================================================
#
#  This file tells Ansible WHERE to connect.
#  It defines your Azure VM as the single target host.
#
# =============================================================================

[dltrf_servers]
dltrf-azure ansible_host=20.212.82.99

[dltrf_servers:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/dltrf-server_key.pem
ansible_python_interpreter=/usr/bin/python3

# Fix for a common SSH warning on first connections
ansible_ssh_common_args='-o StrictHostKeyChecking=no'